### ISSUE TITLE
Populate database with dummy data for testing

### ISSUE THREAD

**Issue by Fehings** [Clayton-TV/claytontv#36]
We need some dummy data to test the search and browse functionality. Can use generators for this that give us pseudo random data which is formatted to be close to the real thing.

- [x] Generate artificial dummy data (use a generator to make sure the data is similar in form to our real data)
- [x]  Add a couple of data entries with data from the master spreadsheet to ensure we have some real videos in the database that we can use for testing embedding
- [x] Import the dummy data into the database (either csv import directly or with django handling of imports).

**Comment by Ettie-ClaytonTV** [comment]
[VideoTestingData2.csv](https://github.com/user-attachments/files/16036610/VideoTestingData2.csv)
[VideoTestingRealDataExample.csv](https://github.com/user-attachments/files/16036611/VideoTestingRealDataExample.csv)
Can someone check this data for me and see if there's any errors?

**Comment by Fehings** [comment]
So I am marking these as done though we have used a different approach to the one we thought we were going to. Ended up using Django seed to add these and then adding real data manually for now. We do need to have a bulk upload option for real data but that is a different issue. Therefore marking this as closed - please see the Wiki page on generating dummy data for the final solution to this issue.
